### ISSUE TITLE
How to use in my project

### ISSUE THREAD

**Issue by EryouHao** [traff/monaco-markdown#1]
Hello, author, how do I use `monaco-markdown` in my project?

Maybe I need to install from npm, then run `gulp dist`, and then use it in the project like demo? Is there a simpler way?

my project use vue + typescript

Thank you for your work.

**Comment by EryouHao** [comment]
If you need development assistance, I am willing to participate in the development.

**Comment by EryouHao** [comment]
If you need development assistance, I am willing to participate in the development.

**Comment by trofimander** [comment]
Hi! Yes, there is a corresponding npm package: https://www.npmjs.com/package/monaco-markdown

**Comment by trofimander** [comment]
>If you need development assistance, I am willing to participate in the development.

Please feel free create issues if anything is missing in functionality and then submit a pull-request.
